name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Install CGAL 5
      run: |
        # Leave that here in case we ever need a PPA again
        sudo apt-get install -y software-properties-common
        sudo apt-add-repository -y ppa:nschloe/cgal-backports
        sudo apt update
        sudo apt install -y libcgal-dev
    - name: Install other dependencies
      run: |
        sudo apt-get install -y libeigen3-dev python3-pip clang
    - name: Test with tox
      run: |
        pip install tox
        CC="clang" tox -- --cov pygalmesh --cov-report xml --cov-report term
    - uses: codecov/codecov-action@v1
