name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Don't use lfs directly, but cache the lfs results.
      # See <https://github.com/actions/checkout/issues/165#issuecomment-657673315>.
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   lfs: true
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: git lfs pull

      - name: Install CGAL 5
        run: |
          # Leave that here in case we ever need a PPA again
          # sudo apt-get install -y software-properties-common
          # sudo apt-add-repository -y ppa:nschloe/cgal-backports
          # sudo apt update
          sudo apt install -y libcgal-dev
      - name: Install other dependencies
        run: |
          sudo apt-get install -y libeigen3-dev python3-pip clang
      - name: Test with tox
        run: |
          pip install tox
          CC="clang" tox -- --cov pygalmesh --cov-report xml --cov-report term
      - uses: codecov/codecov-action@v1

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Don't use lfs directly, but cache the lfs results.
      # See <https://github.com/actions/checkout/issues/165#issuecomment-657673315>.
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   lfs: true
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: git lfs pull

      - name: Install system dependencies
        run: |
          brew install cgal eigen
      - name: Test with tox
        run: |
          pip install tox
          CC="clang" tox -- --cov pygalmesh --cov-report xml --cov-report term
